name: AllAPILoader
main: OhhhAlex\AllAPILoader\Main
version: 2.1
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: TheNewHEROBRINE - OhhhAlex Copy
description: Makes the server load every plugin regardless of the API version
load: STARTUP
softdepend: ["DevTools", "FolderPluginLoader"]
